apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default
resources:
  - ../../bases/crds
  - ../../bases/rails
  - ../../bases/rbac
  - ../../bases/cron
  - namespace.yaml
images:
- name: ghcr.io/kingdonb/stats-tracker-ghcr
  newName: ghcr.io/kingdonb/stats-tracker-ghcr
  newTag: 0.1.1
patches:
- patch: |
    - op: replace
      path: /spec/jobTemplate/spec/template/spec/containers/0/imagePullPolicy
      value: IfNotPresent
  target:
    kind: CronJob
    name: stats-tracker-ghcr
