apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default
resources:
  - ../../bases/crds
  - ../../bases/rails
  - ../../bases/rbac
  - ../../bases/cron
  - namespace.yaml
# transformers:
#   - labels.yaml
