---
apiVersion: "apiextensions.k8s.io/v1"
kind: "CustomResourceDefinition"
metadata:
  name: "projects.example.com"
spec:
  group: "example.com"
  names:
    plural: "projects"
    singular: "project"
    kind: "Project"
  scope: "Namespaced"
  versions:
  - name: "v1alpha1"
    schema:
      openAPIV3Schema:
        required: ["spec"]
        properties:
          spec:
            required: ["projectName"]
            properties:
              projectName:
                type: "string"
                minimum: 1
            type: object
          status:
            properties:
              count:
                type: "string"
                minimum: 1
              lastUpdate:
                type: "string"
                minimum: 1
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
---
apiVersion: "apiextensions.k8s.io/v1"
kind: "CustomResourceDefinition"
metadata:
  name: "leaves.example.com"
spec:
  group: "example.com"
  names:
    plural: "leaves"
    singular: "leaf"
    kind: "Leaf"
  scope: "Namespaced"
  versions:
  - name: "v1alpha1"
    schema:
      openAPIV3Schema:
        required: ["spec"]
        properties:
          spec:
            required: ["repoName", "projectName", "packageName"]
            properties:
              repoName:
                type: "string"
                minimum: 1
              projectName:
                type: "string"
                minimum: 1
              packageName:
                type: "string"
                minimum: 1
            type: object
          status:
            properties:
              count:
                type: "string"
                minimum: 1
              lastUpdate:
                type: "string"
                minimum: 1
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
